spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/capstoneDB
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
